=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IFClient::CreateVolumeParam
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateVolumeParam' do
  before do
    # run before each test
    @instance = IFClient::CreateVolumeParam.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateVolumeParam' do
    it 'should create an instance of CreateVolumeParam' do
      expect(@instance).to be_instance_of(IFClient::CreateVolumeParam)
    end
  end
  describe 'test attribute "arg0_volume"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "arg1_inherit_san_view_settings_from_project"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

