=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for IFClient::NasApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NasApi' do
  before do
    # run before each test
    @instance = IFClient::NasApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NasApi' do
    it 'should create an instance of NasApi' do
      expect(@instance).to be_instance_of(IFClient::NasApi)
    end
  end

  # unit tests for add_nfs_network_acl_on_project_post
  # Add network ACL to NFS Project
  # 
  # @param add_nfs_network_acl_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'add_nfs_network_acl_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for add_nfs_network_acl_on_share_post
  # Add network ACL to NFS share
  # 
  # @param add_nfs_network_acl_on_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'add_nfs_network_acl_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_nfs_network_ac_ls_on_project_post
  # Returns all the Network ACLs for the NFS Project
  # 
  # @param get_nfs_network_ac_ls_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [Array<NetworkACLV21>]
  describe 'get_nfs_network_ac_ls_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_nfs_network_ac_ls_on_share_post
  # Returns all the Network ACLs for the NFS share
  # 
  # @param get_nfs_network_ac_ls_on_share_param 
  # @param [Hash] opts the optional parameters
  # @return [Array<NetworkACLV21>]
  describe 'get_nfs_network_ac_ls_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for inherit_network_ac_lsettings_from_project_post
  # Set the share property to inherit NFS or SMB ACL settings from project.
  # 
  # @param inherit_network_ac_lsettings_from_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'inherit_network_ac_lsettings_from_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for is_project_exposed_over_nfs_post
  # Returns whether the NFS protocol is enabled for the Project
  # 
  # @param is_project_exposed_over_nfs_param 
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'is_project_exposed_over_nfs_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for is_project_exposed_over_smb_post
  # Returns whether the SMB protocol is enabled for the Project
  # 
  # @param is_project_exposed_over_smb_param 
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'is_project_exposed_over_smb_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for is_share_exposed_over_nfs_post
  # Returns whether the NFS protocol is enabled for the share
  # 
  # @param is_share_exposed_over_nfs_param 
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'is_share_exposed_over_nfs_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for is_share_exposed_over_smb_post
  # Returns whether the SMB protocol is enabled for the share
  # 
  # @param is_share_exposed_over_smb_param 
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'is_share_exposed_over_smb_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_all_nfs_network_ac_ls_on_project_post
  # Remove All network ACLs from NFS Project
  # 
  # @param remove_all_nfs_network_ac_ls_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'remove_all_nfs_network_ac_ls_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_all_nfs_network_ac_ls_on_share_post
  # Remove All network ACLs from NFS share
  # 
  # @param remove_all_nfs_network_ac_ls_on_share_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'remove_all_nfs_network_ac_ls_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_nfs_network_acl_on_project_post
  # Remove network ACL from NFS Project
  # 
  # @param remove_nfs_network_acl_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'remove_nfs_network_acl_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_nfs_network_acl_on_share_post
  # Remove network ACL from NFS share
  # 
  # @param remove_nfs_network_acl_on_share_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'remove_nfs_network_acl_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_nfs_network_ac_ls_on_project_post
  # Set the network ACLS on the NFS Project If the dataset contains any network ACLs, they will be removed as well.
  # 
  # @param set_nfs_network_ac_ls_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'set_nfs_network_ac_ls_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_nfs_network_ac_ls_on_share_post
  # Set the network ACLS on the NFS share. If the dataset contains any network ACLs, they will be removed as well.
  # 
  # @param set_nfs_network_ac_ls_on_share_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'set_nfs_network_ac_ls_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_nfs_sharing_on_project_post
  # Enable/Disable NFS protocol for a Project
  # 
  # @param set_nfs_sharing_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'set_nfs_sharing_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_nfs_sharing_on_share_post
  # Enable/Disable NFS protocol for a share. If the dataset contains any network ACLs, they will be removed as well.
  # 
  # @param set_nfs_sharing_on_share_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'set_nfs_sharing_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_smb_sharing_on_project_post
  # Enable/Disable SMB protocol for a Project, If the dataset contains any network ACLs, they are removed as well.
  # 
  # @param set_smb_sharing_on_project_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'set_smb_sharing_on_project_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_smb_sharing_on_share_post
  # Enable/Disable SMB protocol for a share. If the dataset contains any network ACLs, they will be removed as well.
  # 
  # @param set_smb_sharing_on_share_param 
  # @param [Hash] opts the optional parameters
  # @return [COMMANDSTATUS]
  describe 'set_smb_sharing_on_share_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
