=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module IFClient

  class LunStatus
    # indicating whether the LUN is:   active (0)   active to standby (1)   standby (2)   standby to active (3) 
    attr_accessor :access_state

    # The LUN alias, if specified.
    attr_accessor :_alias

    # The block size of the LUN.
    attr_accessor :block_size

    attr_accessor :command_exception

    attr_accessor :command_status

    # The data file path for the LUN.
    attr_accessor :data_file

    # The path to the dataset. The dataset path should have the format PoolName/Local/ProjectName/VolumeName for LUNs. 
    attr_accessor :dataset_path

    # The lunId of the LUN.
    attr_accessor :guid

    # The meta file path of the LUN.
    attr_accessor :meta_file

    # The management URL of the LUN.
    attr_accessor :mgmt_url

    # Operational status of the LU.     Stmf (SCSI target mode framework) logical unit offline (0)     Stmf logical unit offlining (1)     Stmf logical unit online (2)     Stmf logical unit onlining (3)     Stmf logical unit unregistered (4) 
    attr_accessor :operational_status

    # Field not used.
    attr_accessor :product_id

    # Field not used.
    attr_accessor :serial_number

    # The size of the LUN.
    attr_accessor :size

    # Field not used.
    attr_accessor :vendor_id

    # The number of mappings defined for the LUN.
    attr_accessor :view_count

    # Indicates if the data write cache is disabled.
    attr_accessor :write_cache_disable

    # Indicates if write protect is enabled or disabled.   Read-Only (True)   Write (False) 
    attr_accessor :write_protect


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'access_state' => :'accessState',
        :'_alias' => :'alias',
        :'block_size' => :'blockSize',
        :'command_exception' => :'commandException',
        :'command_status' => :'commandStatus',
        :'data_file' => :'dataFile',
        :'dataset_path' => :'datasetPath',
        :'guid' => :'guid',
        :'meta_file' => :'metaFile',
        :'mgmt_url' => :'mgmtURL',
        :'operational_status' => :'operationalStatus',
        :'product_id' => :'productId',
        :'serial_number' => :'serialNumber',
        :'size' => :'size',
        :'vendor_id' => :'vendorId',
        :'view_count' => :'viewCount',
        :'write_cache_disable' => :'writeCacheDisable',
        :'write_protect' => :'writeProtect'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'access_state' => :'Integer',
        :'_alias' => :'String',
        :'block_size' => :'String',
        :'command_exception' => :'ErrorModel',
        :'command_status' => :'COMMAND_STATUS',
        :'data_file' => :'String',
        :'dataset_path' => :'String',
        :'guid' => :'String',
        :'meta_file' => :'String',
        :'mgmt_url' => :'String',
        :'operational_status' => :'Integer',
        :'product_id' => :'String',
        :'serial_number' => :'String',
        :'size' => :'String',
        :'vendor_id' => :'String',
        :'view_count' => :'Integer',
        :'write_cache_disable' => :'BOOLEAN',
        :'write_protect' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'accessState')
        self.access_state = attributes[:'accessState']
      end

      if attributes.has_key?(:'alias')
        self._alias = attributes[:'alias']
      end

      if attributes.has_key?(:'blockSize')
        self.block_size = attributes[:'blockSize']
      end

      if attributes.has_key?(:'commandException')
        self.command_exception = attributes[:'commandException']
      end

      if attributes.has_key?(:'commandStatus')
        self.command_status = attributes[:'commandStatus']
      end

      if attributes.has_key?(:'dataFile')
        self.data_file = attributes[:'dataFile']
      end

      if attributes.has_key?(:'datasetPath')
        self.dataset_path = attributes[:'datasetPath']
      end

      if attributes.has_key?(:'guid')
        self.guid = attributes[:'guid']
      end

      if attributes.has_key?(:'metaFile')
        self.meta_file = attributes[:'metaFile']
      end

      if attributes.has_key?(:'mgmtURL')
        self.mgmt_url = attributes[:'mgmtURL']
      end

      if attributes.has_key?(:'operationalStatus')
        self.operational_status = attributes[:'operationalStatus']
      end

      if attributes.has_key?(:'productId')
        self.product_id = attributes[:'productId']
      end

      if attributes.has_key?(:'serialNumber')
        self.serial_number = attributes[:'serialNumber']
      end

      if attributes.has_key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.has_key?(:'vendorId')
        self.vendor_id = attributes[:'vendorId']
      end

      if attributes.has_key?(:'viewCount')
        self.view_count = attributes[:'viewCount']
      end

      if attributes.has_key?(:'writeCacheDisable')
        self.write_cache_disable = attributes[:'writeCacheDisable']
      end

      if attributes.has_key?(:'writeProtect')
        self.write_protect = attributes[:'writeProtect']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          access_state == o.access_state &&
          _alias == o._alias &&
          block_size == o.block_size &&
          command_exception == o.command_exception &&
          command_status == o.command_status &&
          data_file == o.data_file &&
          dataset_path == o.dataset_path &&
          guid == o.guid &&
          meta_file == o.meta_file &&
          mgmt_url == o.mgmt_url &&
          operational_status == o.operational_status &&
          product_id == o.product_id &&
          serial_number == o.serial_number &&
          size == o.size &&
          vendor_id == o.vendor_id &&
          view_count == o.view_count &&
          write_cache_disable == o.write_cache_disable &&
          write_protect == o.write_protect
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [access_state, _alias, block_size, command_exception, command_status, data_file, dataset_path, guid, meta_file, mgmt_url, operational_status, product_id, serial_number, size, vendor_id, view_count, write_cache_disable, write_protect].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = IFClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
