=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'date'

module IFClient

  class SubProjectV21
    # Name of the project.
    attr_accessor :project_name

    # The pool in which the project exists.
    attr_accessor :pool_name

    # Indicates whether the project belongs to the current Tegile array.
    attr_accessor :local_dataset

    # Purpose of the dataset.
    attr_accessor :purpose

    # Compression algorithm, default value: \"lz4\"  
    attr_accessor :compression

    # Log compression, default value : \"off\" 
    attr_accessor :compressed_log

    # Deduplication setting, default value: \"on\" 
    attr_accessor :dedup

    # Number of data copies, default value: \"1\" 
    attr_accessor :copies

    # Primary cache specified, default value: \"all\" 
    attr_accessor :primary_cache

    # Secondary cache specified, default value: \"all\" 
    attr_accessor :secondary_cache

    # Read only flag, default value: \"off\" 
    attr_accessor :readonly

    # Prejudice in favor of log, default value: \"latency\" 
    attr_accessor :logbias

    # synchronization mode, default value: \"standard\"  
    attr_accessor :sync

    # This field is a string that uniquely identifies the volume on a Tegile array. A dataset path should have the format: PoolName/Local/ProjectName 
    attr_accessor :zfs_data_set_name

    # Name of the subproject
    attr_accessor :name

    # Global unique identifier of the sub project
    attr_accessor :guid

    # Toggle override parent project compression algorithm
    attr_accessor :override_compression

    # Reserved space number of the sub project
    attr_accessor :reservation_in_byte

    # Reserved space in reserved space metric unit of the sub project
    attr_accessor :reservation

    # reserved space metric unit of the sub project
    attr_accessor :reservation_metric

    # Enable reservation feature
    attr_accessor :reservation_enabled

    # Toggle overwrite parent project deduplication
    attr_accessor :override_dedup

    # Toggle overwrite copies of parent project
    attr_accessor :override_copies

    # Toggle overwrite parent project primary cache
    attr_accessor :override_primary_cache

    # Toggle overwrite parent project secondary cache
    attr_accessor :override_secondary_cache

    # Toggle overwrite parent readonly feature
    attr_accessor :override_readonly

    # Toggle overwrite parent project log bias
    attr_accessor :override_logbias

    # Toggle synchronization mode of the sub project
    attr_accessor :override_sync

    # Toggle overwrite parent project snapshot setting
    attr_accessor :override_project_snapshot_settings

    # Toggle overwrite project parent log compression
    attr_accessor :override_compressed_log

    # The name of the container, \"Local\" or \"Replica\"
    attr_accessor :container_name


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'project_name' => :'projectName',
        :'pool_name' => :'poolName',
        :'local_dataset' => :'localDataset',
        :'purpose' => :'purpose',
        :'compression' => :'compression',
        :'compressed_log' => :'compressedLog',
        :'dedup' => :'dedup',
        :'copies' => :'copies',
        :'primary_cache' => :'primaryCache',
        :'secondary_cache' => :'secondaryCache',
        :'readonly' => :'readonly',
        :'logbias' => :'logbias',
        :'sync' => :'sync',
        :'zfs_data_set_name' => :'zfsDataSetName',
        :'name' => :'name',
        :'guid' => :'guid',
        :'override_compression' => :'overrideCompression',
        :'reservation_in_byte' => :'reservationInByte',
        :'reservation' => :'reservation',
        :'reservation_metric' => :'reservationMetric',
        :'reservation_enabled' => :'reservationEnabled',
        :'override_dedup' => :'overrideDedup',
        :'override_copies' => :'overrideCopies',
        :'override_primary_cache' => :'overridePrimaryCache',
        :'override_secondary_cache' => :'overrideSecondaryCache',
        :'override_readonly' => :'overrideReadonly',
        :'override_logbias' => :'overrideLogbias',
        :'override_sync' => :'overrideSync',
        :'override_project_snapshot_settings' => :'overrideProjectSnapshotSettings',
        :'override_compressed_log' => :'overrideCompressedLog',
        :'container_name' => :'containerName'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'project_name' => :'String',
        :'pool_name' => :'String',
        :'local_dataset' => :'BOOLEAN',
        :'purpose' => :'String',
        :'compression' => :'String',
        :'compressed_log' => :'String',
        :'dedup' => :'String',
        :'copies' => :'String',
        :'primary_cache' => :'String',
        :'secondary_cache' => :'String',
        :'readonly' => :'String',
        :'logbias' => :'String',
        :'sync' => :'String',
        :'zfs_data_set_name' => :'String',
        :'name' => :'String',
        :'guid' => :'String',
        :'override_compression' => :'BOOLEAN',
        :'reservation_in_byte' => :'Integer',
        :'reservation' => :'Float',
        :'reservation_metric' => :'String',
        :'reservation_enabled' => :'BOOLEAN',
        :'override_dedup' => :'BOOLEAN',
        :'override_copies' => :'BOOLEAN',
        :'override_primary_cache' => :'BOOLEAN',
        :'override_secondary_cache' => :'BOOLEAN',
        :'override_readonly' => :'BOOLEAN',
        :'override_logbias' => :'BOOLEAN',
        :'override_sync' => :'BOOLEAN',
        :'override_project_snapshot_settings' => :'BOOLEAN',
        :'override_compressed_log' => :'BOOLEAN',
        :'container_name' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'projectName')
        self.project_name = attributes[:'projectName']
      end

      if attributes.has_key?(:'poolName')
        self.pool_name = attributes[:'poolName']
      end

      if attributes.has_key?(:'localDataset')
        self.local_dataset = attributes[:'localDataset']
      end

      if attributes.has_key?(:'purpose')
        self.purpose = attributes[:'purpose']
      end

      if attributes.has_key?(:'compression')
        self.compression = attributes[:'compression']
      end

      if attributes.has_key?(:'compressedLog')
        self.compressed_log = attributes[:'compressedLog']
      end

      if attributes.has_key?(:'dedup')
        self.dedup = attributes[:'dedup']
      end

      if attributes.has_key?(:'copies')
        self.copies = attributes[:'copies']
      end

      if attributes.has_key?(:'primaryCache')
        self.primary_cache = attributes[:'primaryCache']
      end

      if attributes.has_key?(:'secondaryCache')
        self.secondary_cache = attributes[:'secondaryCache']
      end

      if attributes.has_key?(:'readonly')
        self.readonly = attributes[:'readonly']
      end

      if attributes.has_key?(:'logbias')
        self.logbias = attributes[:'logbias']
      end

      if attributes.has_key?(:'sync')
        self.sync = attributes[:'sync']
      end

      if attributes.has_key?(:'zfsDataSetName')
        self.zfs_data_set_name = attributes[:'zfsDataSetName']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'guid')
        self.guid = attributes[:'guid']
      end

      if attributes.has_key?(:'overrideCompression')
        self.override_compression = attributes[:'overrideCompression']
      end

      if attributes.has_key?(:'reservationInByte')
        self.reservation_in_byte = attributes[:'reservationInByte']
      end

      if attributes.has_key?(:'reservation')
        self.reservation = attributes[:'reservation']
      end

      if attributes.has_key?(:'reservationMetric')
        self.reservation_metric = attributes[:'reservationMetric']
      end

      if attributes.has_key?(:'reservationEnabled')
        self.reservation_enabled = attributes[:'reservationEnabled']
      end

      if attributes.has_key?(:'overrideDedup')
        self.override_dedup = attributes[:'overrideDedup']
      end

      if attributes.has_key?(:'overrideCopies')
        self.override_copies = attributes[:'overrideCopies']
      end

      if attributes.has_key?(:'overridePrimaryCache')
        self.override_primary_cache = attributes[:'overridePrimaryCache']
      end

      if attributes.has_key?(:'overrideSecondaryCache')
        self.override_secondary_cache = attributes[:'overrideSecondaryCache']
      end

      if attributes.has_key?(:'overrideReadonly')
        self.override_readonly = attributes[:'overrideReadonly']
      end

      if attributes.has_key?(:'overrideLogbias')
        self.override_logbias = attributes[:'overrideLogbias']
      end

      if attributes.has_key?(:'overrideSync')
        self.override_sync = attributes[:'overrideSync']
      end

      if attributes.has_key?(:'overrideProjectSnapshotSettings')
        self.override_project_snapshot_settings = attributes[:'overrideProjectSnapshotSettings']
      end

      if attributes.has_key?(:'overrideCompressedLog')
        self.override_compressed_log = attributes[:'overrideCompressedLog']
      end

      if attributes.has_key?(:'containerName')
        self.container_name = attributes[:'containerName']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @project_name.nil?
        invalid_properties.push("invalid value for 'project_name', project_name cannot be nil.")
      end

      if @pool_name.nil?
        invalid_properties.push("invalid value for 'pool_name', pool_name cannot be nil.")
      end

      if @local_dataset.nil?
        invalid_properties.push("invalid value for 'local_dataset', local_dataset cannot be nil.")
      end

      if @name.nil?
        invalid_properties.push("invalid value for 'name', name cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @project_name.nil?
      return false if @pool_name.nil?
      return false if @local_dataset.nil?
      return false if @name.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          project_name == o.project_name &&
          pool_name == o.pool_name &&
          local_dataset == o.local_dataset &&
          purpose == o.purpose &&
          compression == o.compression &&
          compressed_log == o.compressed_log &&
          dedup == o.dedup &&
          copies == o.copies &&
          primary_cache == o.primary_cache &&
          secondary_cache == o.secondary_cache &&
          readonly == o.readonly &&
          logbias == o.logbias &&
          sync == o.sync &&
          zfs_data_set_name == o.zfs_data_set_name &&
          name == o.name &&
          guid == o.guid &&
          override_compression == o.override_compression &&
          reservation_in_byte == o.reservation_in_byte &&
          reservation == o.reservation &&
          reservation_metric == o.reservation_metric &&
          reservation_enabled == o.reservation_enabled &&
          override_dedup == o.override_dedup &&
          override_copies == o.override_copies &&
          override_primary_cache == o.override_primary_cache &&
          override_secondary_cache == o.override_secondary_cache &&
          override_readonly == o.override_readonly &&
          override_logbias == o.override_logbias &&
          override_sync == o.override_sync &&
          override_project_snapshot_settings == o.override_project_snapshot_settings &&
          override_compressed_log == o.override_compressed_log &&
          container_name == o.container_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [project_name, pool_name, local_dataset, purpose, compression, compressed_log, dedup, copies, primary_cache, secondary_cache, readonly, logbias, sync, zfs_data_set_name, name, guid, override_compression, reservation_in_byte, reservation, reservation_metric, reservation_enabled, override_dedup, override_copies, override_primary_cache, override_secondary_cache, override_readonly, override_logbias, override_sync, override_project_snapshot_settings, override_compressed_log, container_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = IFClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
