=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require "uri"

module IFClient
  class SystemApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Lists values of the requested system properties for a Tegile array.
    # 
    # @param list_system_properties_param 
    # @param [Hash] opts the optional parameters
    # @return [Array<String>]
    def list_system_properties_post(list_system_properties_param, opts = {})
      data, _status_code, _headers = list_system_properties_post_with_http_info(list_system_properties_param, opts)
      return data
    end

    # Lists values of the requested system properties for a Tegile array.
    # 
    # @param list_system_properties_param 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<String>, Fixnum, Hash)>] Array<String> data, response status code and response headers
    def list_system_properties_post_with_http_info(list_system_properties_param, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SystemApi.list_system_properties_post ..."
      end
      # verify the required parameter 'list_system_properties_param' is set
      if @api_client.config.client_side_validation && list_system_properties_param.nil?
        fail ArgumentError, "Missing the required parameter 'list_system_properties_param' when calling SystemApi.list_system_properties_post"
      end
      # resource path
      local_var_path = "/listSystemProperties"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(list_system_properties_param)
      auth_names = ['basicAuth']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<String>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemApi#list_system_properties_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
