=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for IFClient::ReplicationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReplicationApi' do
  before do
    # run before each test
    @instance = IFClient::ReplicationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReplicationApi' do
    it 'should create an instance of ReplicationApi' do
      expect(@instance).to be_instance_of(IFClient::ReplicationApi)
    end
  end

  # unit tests for get_replication_config_list_post
  # Lists all the replication configurations for the specified project.
  # 
  # @param get_replication_config_list_param 
  # @param [Hash] opts the optional parameters
  # @return [Array<ReplicationConfig_V1_2>]
  describe 'get_replication_config_list_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_replication_status_post
  # Gets the replication status for the specified replication configuration.
  # 
  # @param get_replication_status_param 
  # @param [Hash] opts the optional parameters
  # @return [ReplicationStatus_V1_2]
  describe 'get_replication_status_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for start_replication_post
  # Starts a replication for the specified replication configuration.
  # 
  # @param start_replication_param 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'start_replication_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
