=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

# Common files
require 'tegile-api/api_client'
require 'tegile-api/api_error'
require 'tegile-api/version'
require 'tegile-api/configuration'

# Models
require 'tegile-api/models/add_initiator_to_initiator_group_param'
require 'tegile-api/models/add_nfs_network_acl_on_param'
require 'tegile-api/models/add_nfs_network_acl_on_project_param'
require 'tegile-api/models/base_dataset_v2_1'
require 'tegile-api/models/block_size_enum'
require 'tegile-api/models/command_status'
require 'tegile-api/models/clone_project_snapshot_param'
require 'tegile-api/models/clone_share_snapshot_param'
require 'tegile-api/models/clone_volume_snapshot_param'
require 'tegile-api/models/create_fc_initiator_param'
require 'tegile-api/models/create_iscsi_target_for_group_param'
require 'tegile-api/models/create_iscsi_target_param'
require 'tegile-api/models/create_initiator_group_param'
require 'tegile-api/models/create_iscsi_initiator_param'
require 'tegile-api/models/create_mapping_for_project_param'
require 'tegile-api/models/create_mapping_for_volume_param'
require 'tegile-api/models/create_project_param'
require 'tegile-api/models/create_project_snapshot_param'
require 'tegile-api/models/create_share_param'
require 'tegile-api/models/create_share_snapshot_param'
require 'tegile-api/models/create_target_group_param'
require 'tegile-api/models/create_volume_param'
require 'tegile-api/models/create_volume_snapshot_param'
require 'tegile-api/models/delete_dataset_param'
require 'tegile-api/models/delete_iscsi_initiator_param'
require 'tegile-api/models/delete_iscsi_target_param'
require 'tegile-api/models/delete_initiator_group_param'
require 'tegile-api/models/delete_mapping_from_project_param'
require 'tegile-api/models/delete_mapping_from_volume_param'
require 'tegile-api/models/delete_project_snapshot_param'
require 'tegile-api/models/delete_share_param'
require 'tegile-api/models/delete_share_snapshot_param'
require 'tegile-api/models/delete_target_group_param'
require 'tegile-api/models/delete_volume_param'
require 'tegile-api/models/delete_volume_snapshot_param'
require 'tegile-api/models/error_code'
require 'tegile-api/models/error_model'
require 'tegile-api/models/fc_initiator_v2_1'
require 'tegile-api/models/fc_target_v2_1'
require 'tegile-api/models/get_initiator_group_param'
require 'tegile-api/models/get_nfs_network_ac_ls_on_project_param'
require 'tegile-api/models/get_nfs_network_ac_ls_on_share_param'
require 'tegile-api/models/get_project_default_fc_it_view_param'
require 'tegile-api/models/get_project_default_iscsi_it_view_param'
require 'tegile-api/models/get_project_param'
require 'tegile-api/models/get_project_snapshot_creation_status_param'
require 'tegile-api/models/get_replication_config_list_param'
require 'tegile-api/models/get_replication_status_param'
require 'tegile-api/models/get_share_param'
require 'tegile-api/models/get_share_snapshot_creation_status_param'
require 'tegile-api/models/get_volume_it_view_param'
require 'tegile-api/models/get_volume_param'
require 'tegile-api/models/get_volume_snapshot_creation_status_param'
require 'tegile-api/models/iscsi_initiator_v2_1'
require 'tegile-api/models/iscsi_target_create_v2_1'
require 'tegile-api/models/iscsi_target_v2_1'
require 'tegile-api/models/it_view_v2_1'
require 'tegile-api/models/inherit_property_from_project_param'
require 'tegile-api/models/initiator_group_exists_param'
require 'tegile-api/models/initiator_group_v2_1'
require 'tegile-api/models/is_project_exposed_over_nfs_param'
require 'tegile-api/models/is_share_exposed_over_nfs_param'
require 'tegile-api/models/iscsi_initiator_v1_0'
require 'tegile-api/models/list_fc_initiators_param'
require 'tegile-api/models/list_fc_targets_param'
require 'tegile-api/models/list_iscsi_initiators_param'
require 'tegile-api/models/list_iscsi_targets_param'
require 'tegile-api/models/list_initiators_in_initiator_group_param'
require 'tegile-api/models/list_luns_by_id_param'
require 'tegile-api/models/list_projects_param'
require 'tegile-api/models/list_shares_param'
require 'tegile-api/models/list_snapshots_param'
require 'tegile-api/models/list_system_properties_param'
require 'tegile-api/models/list_targets_in_target_group_param'
require 'tegile-api/models/list_volumes_param'
require 'tegile-api/models/local_group_v1_2'
require 'tegile-api/models/local_user_v1_2'
require 'tegile-api/models/lun_status'
require 'tegile-api/models/mode_enum'
require 'tegile-api/models/modify_project_properties_param'
require 'tegile-api/models/modify_share_properties_param'
require 'tegile-api/models/modify_volume_properties_param'
require 'tegile-api/models/move_target_to_target_group_param'
require 'tegile-api/models/network_acl_v2_1'
require 'tegile-api/models/param'
require 'tegile-api/models/param_1'
require 'tegile-api/models/param_2'
require 'tegile-api/models/permission_type_enum'
require 'tegile-api/models/pool_v1_0'
require 'tegile-api/models/project_clone_progress_status_v1_2'
require 'tegile-api/models/project_v1_0'
require 'tegile-api/models/project_v1_2'
require 'tegile-api/models/remove_all_nfs_network_ac_ls_on_project_param'
require 'tegile-api/models/remove_all_nfs_network_ac_ls_on_share_param'
require 'tegile-api/models/remove_nfs_network_acl_on_project_param'
require 'tegile-api/models/remove_nfs_network_acl_on_share_param'
require 'tegile-api/models/replication_config_v1_2'
require 'tegile-api/models/replication_scope_option'
require 'tegile-api/models/replication_status_v1_2'
require 'tegile-api/models/roll_back_to_project_snapshot_param'
require 'tegile-api/models/roll_back_to_volume_snapshot_param'
require 'tegile-api/models/snapshot_deletion_status'
require 'tegile-api/models/snapshot_progress_status'
require 'tegile-api/models/set_nfs_network_ac_ls_on_project_param'
require 'tegile-api/models/set_nfs_network_ac_ls_on_share_param'
require 'tegile-api/models/set_nfs_sharing_on_project_param'
require 'tegile-api/models/set_nfs_sharing_on_share_param'
require 'tegile-api/models/share_options'
require 'tegile-api/models/share_permissions'
require 'tegile-api/models/share_v1_0'
require 'tegile-api/models/snap_shot_deletion_status'
require 'tegile-api/models/snapshot_progress_status'
require 'tegile-api/models/start_replication_param'
require 'tegile-api/models/state'
require 'tegile-api/models/user_acl_v2_1'
require 'tegile-api/models/volume_v1_0'
require 'tegile-api/models/zebi_system_property'
require 'tegile-api/models/project_v2_1'
require 'tegile-api/models/sub_project_v2_1'
require 'tegile-api/models/share_v2_1'
require 'tegile-api/models/volume_v2_1'

# APIs
require 'tegile-api/api/data_api'
require 'tegile-api/api/nas_api'
require 'tegile-api/api/replication_api'
require 'tegile-api/api/san_api'
require 'tegile-api/api/snapshot_api'
require 'tegile-api/api/system_api'

module IFClient
  class << self
    # Customize default settings for the SDK using block.
    #   IFClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
