=begin
#Tegile IntelliFlassh WEB API

#WEB API for managing Tegile IntelliFlash Arrays.

OpenAPI spec version: 2.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IFClient::SNAPSHOT_PROGRESS_STATUS
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SNAPSHOT_PROGRESS_STATUS' do
  before do
    # run before each test
    @instance = IFClient::SNAPSHOT_PROGRESS_STATUS.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SNAPSHOT_PROGRESS_STATUS' do
    it 'should create an instance of SNAPSHOT_PROGRESS_STATUS' do
      expect(@instance).to be_instance_of(IFClient::SNAPSHOT_PROGRESS_STATUS)
    end
  end
end

